language: python

#Set up the basic environment to be python
python:
  - "3.8.5"

install:
  #Install all the requirements
  - pip install -r requirements.txt

script:
  # Run tests
  - python -m pytest